# Generated by Django 3.2.9 on 2022-01-09 18:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_auto_20220109_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Doctors/', verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('open_time', models.TimeField(blank=True, null=True, verbose_name='open_time')),
                ('close_time', models.TimeField(blank=True, null=True, verbose_name='close_time')),
                ('days', models.TextField(blank=True, null=True, verbose_name='days')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='advertising',
            name='center',
        ),
        migrations.RemoveField(
            model_name='center_image',
            name='center',
        ),
        migrations.RemoveField(
            model_name='centeropinion',
            name='center',
        ),
        migrations.RemoveField(
            model_name='centeropinion',
            name='user',
        ),
        migrations.DeleteModel(
            name='news',
        ),
        migrations.DeleteModel(
            name='notification',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='service',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='service',
            name='center',
        ),
        migrations.RemoveField(
            model_name='service',
            name='label',
        ),
        migrations.RemoveField(
            model_name='service_image',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceopinion',
            name='service',
        ),
        migrations.RemoveField(
            model_name='serviceopinion',
            name='user',
        ),
        migrations.DeleteModel(
            name='advertising',
        ),
        migrations.DeleteModel(
            name='center',
        ),
        migrations.DeleteModel(
            name='Center_image',
        ),
        migrations.DeleteModel(
            name='CenterOpinion',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='reservation',
        ),
        migrations.DeleteModel(
            name='service',
        ),
        migrations.DeleteModel(
            name='Service_image',
        ),
        migrations.DeleteModel(
            name='ServiceOpinion',
        ),
    ]
