# Generated by Django 3.2.9 on 2022-01-09 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0010_doctor_category_hospital_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='Hospital_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospitals', to='commerce.hospital_category'),
        ),
    ]
