# Generated by Django 3.2.9 on 2022-01-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_auto_20220119_1048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='close_time',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='open_time',
        ),
        migrations.AddField(
            model_name='hospital',
            name='time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='time'),
        ),
    ]
