# Generated by Django 3.2.9 on 2022-01-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_auto_20220119_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds',
            field=models.IntegerField(blank=True, null=True, verbose_name='beds'),
        ),
    ]
