# Generated by Django 3.2.9 on 2022-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_hospital_beds'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='DoctorCategories/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctortype',
            name='image',
            field=models.ImageField(default=1, upload_to='DoctorTypes/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='HospitalCategories/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='image',
            field=models.ImageField(default=1, upload_to='HospitalTypes/', verbose_name='image'),
            preserve_default=False,
        ),
    ]
