# Generated by Django 3.2.9 on 2022-01-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_auto_20220121_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='contact'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='contact',
            field=models.TextField(blank=True, null=True, verbose_name='contact'),
        ),
    ]
