# Generated by Django 3.2.9 on 2022-01-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0025_auto_20220122_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='HospitalType',
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='HospitalType',
            field=models.ManyToManyField(blank=True, null=True, related_name='HospitalCategories', to='commerce.HospitalType'),
        ),
    ]
