# Generated by Django 3.2.9 on 2022-01-21 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0026_auto_20220122_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='HospitalType',
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='HospitalType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HospitalCategories', to='commerce.hospitaltype'),
        ),
    ]
