# Generated by Django 3.2.9 on 2022-01-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0028_auto_20220122_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='HospitalType',
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='HospitalType',
            field=models.ManyToManyField(related_name='hospitalCategory', to='commerce.HospitalType', verbose_name='HospitalType'),
        ),
    ]
