# Generated by Django 3.2.9 on 2022-01-24 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0029_auto_20220122_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='doctorcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='doctortype',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='HospitalType',
        ),
        migrations.RemoveField(
            model_name='hospitalcategory',
            name='image',
        ),
        migrations.RemoveField(
            model_name='hospitaltype',
            name='image',
        ),
        migrations.AddField(
            model_name='hospital',
            name='HospitalType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospitals', to='commerce.hospitaltype'),
        ),
    ]
