# Generated by Django 3.2.9 on 2022-01-24 11:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0030_auto_20220124_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='HospitalCategory',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='HospitalType',
        ),
        migrations.AddField(
            model_name='doctorcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='DoctorCategories/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctortype',
            name='image',
            field=models.ImageField(default=1, upload_to='DoctorTypes/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='HospitalType',
            field=models.ManyToManyField(related_name='HospitalCategories', to='commerce.HospitalType', verbose_name='HospitalType'),
        ),
        migrations.AddField(
            model_name='hospitalcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='HospitalCategories/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitaltype',
            name='image',
            field=models.ImageField(default=1, upload_to='HospitalTypes/', verbose_name='image'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PublicHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Hospitals/', verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='time')),
                ('days', models.TextField(blank=True, null=True, verbose_name='days')),
                ('beds', models.IntegerField(blank=True, null=True, verbose_name='beds')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('HospitalCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublicHospitals', to='commerce.hospitalcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PrivateHospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='Hospitals/', verbose_name='image')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('location', models.TextField(blank=True, null=True, verbose_name='location')),
                ('time', models.CharField(blank=True, max_length=255, null=True, verbose_name='time')),
                ('days', models.TextField(blank=True, null=True, verbose_name='days')),
                ('beds', models.IntegerField(blank=True, null=True, verbose_name='beds')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('HospitalCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrivateHospitals', to='commerce.hospitalcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
