# Generated by Django 3.2.9 on 2022-01-24 12:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0031_auto_20220124_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateHospitalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='PrivateHospitalCategories/', verbose_name='image')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PublicHospitalCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='PublicHospitalCategories/', verbose_name='image')),
                ('type', models.CharField(blank=True, max_length=255, null=True, verbose_name='type')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hospital',
            name='PrivateHospitalCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospitals', to='commerce.privatehospitalcategory'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='PublicHospitalCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospitals', to='commerce.publichospitalcategory'),
        ),
    ]
