# Generated by Django 3.2.9 on 2022-01-24 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0032_auto_20220124_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatehospitalcategory',
            name='PrivateHospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PrivateHospitalCategories', to='commerce.privatehospital'),
        ),
        migrations.AddField(
            model_name='publichospitalcategory',
            name='PublicHospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PublicHospitalCategories', to='commerce.publichospital'),
        ),
    ]
